# Generated by Django 3.1.7 on 2022-09-15 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main_website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=30)),
                ('first_name', models.CharField(max_length=100)),
                ('Country_of_residence', models.CharField(max_length=100, null=True)),
                ('driver_license', models.ImageField(null=True, upload_to='driver_license/%d/')),
                ('driver_license_back', models.ImageField(null=True, upload_to='driver_license_back/%d/')),
                ('telephone', models.CharField(max_length=200, null=True)),
                ('countryPhoneCode', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('amount_made', models.CharField(blank=True, default=0.0, max_length=200, null=True)),
                ('amount_deposited', models.CharField(blank=True, default=0.0, max_length=200, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', main_website.models.customUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BitcoinAddresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_wallet', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('enquiry_field', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequestWithdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.IntegerField(default=0.0)),
                ('bitcoin_addresse', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0.0, null=True)),
                ('pricing_plan', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Editable_Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_balance', models.IntegerField(default=0.0)),
                ('closed_tradePL', models.IntegerField(default=0.0)),
                ('deposite_withdrawal', models.IntegerField(default=0.0)),
                ('balance', models.IntegerField(default=0.0)),
                ('total_credit_faculty', models.IntegerField(default=0.0)),
                ('equity', models.IntegerField(default=0.0)),
                ('margin_Requirement', models.IntegerField(default=0.0)),
                ('available_margin', models.IntegerField(default=0.0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Editable Balance',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=100)),
                ('btc_amount_purchased', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
