# Generated by Django 4.0.5 on 2022-07-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.TextField(default=''),
        ),
    ]
